\LoadClass[a4paper]{article}

\RequirePackage{framed}
\RequirePackage{fancyhdr}
\RequirePackage{amsfonts}
\RequirePackage{amsmath}
\RequirePackage{amsthm}
\RequirePackage{ctex}
\RequirePackage{framed}
\RequirePackage{graphicx}
\RequirePackage{float}
\RequirePackage{hyperref}
\RequirePackage{bm}
\RequirePackage{cite}
\RequirePackage{algorithm}
\RequirePackage{algpseudocode}

\def\lt{<}
\def\gt{>}

\newtheorem{theorem}{Theorem}[section]
\newtheorem{axiom}{Axiom}[section]
\newtheorem{lemma}[theorem]{Lemma}
\newtheorem{corollary}[theorem]{Corollary}
\newtheorem{notation}[theorem]{Notation}
\newtheorem{example}[theorem]{Example}
\newtheorem*{remark}{Remark}
\newtheorem{definition}[theorem]{Definition}
\newtheorem{proposition}[theorem]{Props}